spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    owerCaseServiceId: true
server:
 port: 8083
eureka:
 client:
  serviceUrl:
   defaultZone: http://eureka-server:8761/eureka/

